server:
  port: ${INVENTORY_MICROSERVICE_PORT}
spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
  datasource:
    url: jdbc:postgresql://${JDBC_URL:localhost}:${JDBC_PORT:5432}/${JDBC_DATABASE:cardgame}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:postgres}

  sql:
    init:
      mode: always

